# Generated by Django 3.2.8 on 2021-10-20 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_uregister'),
    ]

    operations = [
        migrations.CreateModel(
            name='ULogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=122)),
                ('pswd', models.CharField(max_length=20)),
            ],
        ),
    ]
