# Generated by Django 3.2.8 on 2021-10-20 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_ulogin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ULogin',
        ),
        migrations.DeleteModel(
            name='URegister',
        ),
    ]
